### ISSUE TITLE
pip install zodb fails

### ISSUE THREAD

**Issue by aidiss** [zopefoundation/ZODB#119]
```
C:\Users\admin>pip install zodb
Collecting zodb
  Downloading ZODB-5.0.0.tar.gz (467kB)
    100% |################################| 471kB 1.5MB/s
    Complete output from command python setup.py egg_info:
    warning: no previously-included files matching '*.dll' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching 'coverage.xml' found anywhere in distribution
    no previously-included directories found matching 'docs\_build'
    no previously-included directories found matching 'persistent\__pycache__'
    Traceback (most recent call last):
      File "C:\Users\admin\Anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\admin\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Users\admin\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\admin\anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\command\bdist_egg.py", line 161, in run
      File "c:\users\admin\anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\command\bdist_egg.py", line 147, in call_command
      File "C:\Users\admin\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\admin\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\admin\anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\command\install_lib.py", line 10, in run
      File "C:\Users\admin\Anaconda3\lib\distutils\command\install_lib.py", line 107, in build
        self.run_command('build_ext')
      File "C:\Users\admin\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\admin\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\admin\anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\command\build_ext.py", line 66, in run
      File "C:\Users\admin\Anaconda3\lib\site-packages\Cython\Distutils\build_ext.py", line 164, in run
        _build_ext.build_ext.run(self)
      File "C:\Users\admin\Anaconda3\lib\distutils\command\build_ext.py", line 338, in run
        self.build_extensions()
      File "C:\Users\admin\Anaconda3\lib\site-packages\Cython\Distutils\build_ext.py", line 172, in build_extensions
        self.build_extension(ext)
      File "c:\users\admin\anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\command\build_ext.py", line 178, in build_extension
      File "C:\Users\admin\Anaconda3\lib\distutils\command\build_ext.py", line 532, in build_extension
        depends=ext.depends)
      File "C:\Users\admin\Anaconda3\lib\distutils\_msvccompiler.py", line 306, in compile
        self.initialize()
      File "C:\Users\admin\Anaconda3\lib\distutils\_msvccompiler.py", line 199, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\Users\admin\Anaconda3\lib\distutils\_msvccompiler.py", line 85, in _get_vc_env
        raise DistutilsPlatformError("Unable to find vcvarsall.bat")
    distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\sandbox.py", line 154, in save_modules
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\sandbox.py", line 195, in setup_context
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\sandbox.py", line 243, in run_setup
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\sandbox.py", line 273, in run
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\sandbox.py", line 242, in runner
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\sandbox.py", line 46, in _execfile
      File "C:\Users\admin\AppData\Local\Temp\easy_install-_b_vbbt0\persistent-4.2.1\setup.py", line 115, in <module>
        read_file("CHANGES.rst").decode('latin-1')))
      File "C:\Users\admin\Anaconda3\lib\distutils\core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: Unable to find vcvarsall.bat

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\command\easy_install.py", line 1100, in run_setup
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\sandbox.py", line 246, in run_setup
      File "C:\Users\admin\Anaconda3\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\sandbox.py", line 195, in setup_context
      File "C:\Users\admin\Anaconda3\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\sandbox.py", line 166, in save_modules
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\sandbox.py", line 141, in resume
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\pkg_resources\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\sandbox.py", line 154, in save_modules
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\sandbox.py", line 195, in setup_context
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\sandbox.py", line 243, in run_setup
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\sandbox.py", line 273, in run
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\sandbox.py", line 242, in runner
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\sandbox.py", line 46, in _execfile
      File "C:\Users\admin\AppData\Local\Temp\easy_install-_b_vbbt0\persistent-4.2.1\setup.py", line 115, in <module>
        read_file("CHANGES.rst").decode('latin-1')))
      File "C:\Users\admin\Anaconda3\lib\distutils\core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: Unable to find vcvarsall.bat

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\admin\AppData\Local\Temp\pip-build-f_mm4j39\zodb\setup.py", line 159, in <module>
        include_package_data = True,
      File "C:\Users\admin\Anaconda3\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\dist.py", line 269, in __init__
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\dist.py", line 313, in fetch_build_eggs
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\pkg_resources\__init__.py", line 826, in resolve
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\pkg_resources\__init__.py", line 1092, in best_match
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\pkg_resources\__init__.py", line 1104, in obtain
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\dist.py", line 380, in fetch_build_egg
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\command\easy_install.py", line 664, in easy_install
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\command\easy_install.py", line 694, in install_item
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\command\easy_install.py", line 875, in install_eggs
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\command\easy_install.py", line 1114, in build_and_install
      File "C:\Users\admin\Anaconda3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\command\easy_install.py", line 1102, in run_setup
    distutils.errors.DistutilsError: Setup script exited with error: Unable to find vcvarsall.bat

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\admin\AppData\Local\Temp\pip-build-f_mm4j39\zodb\
```

**Comment by mgedmin** [comment]
The failure happens because ZODB has `setup_requires=['persistent']`, which means it's setuptools itself that's looking for binary eggs (not wheels) on https://pypi.python.org/pypi/persistent/, and there are no binary eggs for Python 3.5 there (because of https://github.com/zopefoundation/zope.wineggbuilder/issues/8).

As a workaround, try to `pip install persistent` before you `pip install ZODB`.  This will allow pip to install the binary `persistent` wheel (rather than egg) that is available on PyPI.

**Comment by jamadden** [comment]
I don't see why `setup_requires` exists in ZODB anymore. It doesn't build any native code anymore. Perhaps that can just be taken out? Or am I forgetting something?
