### ISSUE TITLE
Repozo/Filestorage: TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by zopyx** [zopefoundation/ZODB#259]
Plone 5.2RC1, ZODB 5.5.1, Python 3.6:

```

dgho@server:~/onkopedia_buildout$ bin/repozo --backup --repository /tmp/foo
Traceback (most recent call last):
  File "bin/repozo", line 20, in <module>
    sys.exit(ZODB.scripts.repozo.main())
  File "/home/dgho/onkopedia_buildout/eggs/ZODB-5.5.1-py3.6.egg/ZODB/scripts/repozo.py", line 730, in main
    do_backup(options)
  File "/home/dgho/onkopedia_buildout/eggs/ZODB-5.5.1-py3.6.egg/ZODB/scripts/repozo.py", line 565, in do_backup
    do_full_backup(options)
  File "/home/dgho/onkopedia_buildout/eggs/ZODB-5.5.1-py3.6.egg/ZODB/scripts/repozo.py", line 500, in do_full_backup
    fs = FileStorage(options.file, read_only=True)
  File "/home/dgho/onkopedia_buildout/eggs/ZODB-5.5.1-py3.6.egg/ZODB/FileStorage/FileStorage.py", line 248, in __init__
    self._file_name = os.path.abspath(file_name)
  File "/usr/lib/python3.6/posixpath.py", line 371, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

dgho@server:~/onkopedia_buildout$ bin/python
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by pbauer** [comment]
@zopyx please try aghain with a source-checkout of ZODB. That might have been fixed in the laste changes of repozo by @Sebatyne

**Comment by zopyx** [comment]
No difference with current master.

**Comment by zopyx** [comment]
My backup configuration:

```
[repozo]
recipe = zc.recipe.egg
eggs = ZODB
# or this for an older version:
# eggs = ZODB3
scripts = repozo
dependent-scripts = true

[backup]
recipe = collective.recipe.backup
command = ${buildout:directory}/bin/backup
location = /home/dgho/backup/production/filestorage
blobbackuplocation = /home/dgho/backup/production/blobstorage
keep = 10 

```

```
(Pdb) where
  /home/dgho/onkopedia_buildout/bin/repozo(20)<module>()
-> sys.exit(ZODB.scripts.repozo.main())
  /home/dgho/onkopedia_buildout/src/ZODB/src/ZODB/scripts/repozo.py(796)main()
-> do_backup(options)
  /home/dgho/onkopedia_buildout/src/ZODB/src/ZODB/scripts/repozo.py(588)do_backup()
-> do_full_backup(options)
  /home/dgho/onkopedia_buildout/src/ZODB/src/ZODB/scripts/repozo.py(523)do_full_backup()
-> fs = FileStorage(options.file, read_only=True)
> /home/dgho/onkopedia_buildout/src/ZODB/src/ZODB/FileStorage/FileStorage.py(249)__init__()
-> self._file_name = os.path.abspath(file_name)
(Pdb) file_name
(Pdb) args
self = <ZODB.FileStorage.FileStorage.FileStorage object at 0x7f5703e51978>
file_name = None
create = False
read_only = True
stop = b'\xff\xff\xff\xff\xff\xff\xff\xff'
quota = None
pack_gc = True
pack_keep_old = True
packer = None
blob_dir = None
(Pdb) 
```

**Comment by jamadden** [comment]
According to the documentation, the command line `bin/repozo --backup --repository /tmp/foo` is invalid. [For backup](https://github.com/zopefoundation/ZODB/blob/master/src/ZODB/scripts/repozo.py#L36) the `-f` or `--file` argument (pointing to the data.fs file) is required.

Unfortunately repozo is still using optparse so it doesn't offer clear error messages about missing arguments like that.

**Comment by petschki** [comment]
@zopyx according to your configuration you should use `bin/backup` generated by `collective.recipe.backup` which wraps the repozo command with all the needed options rather than use`bin/repozo` directly

**Comment by zopyx** [comment]
You are right. The commandline parsing code is the problem:

```
bin/repozo --backup
....
--repository is required
```

That's how I came across the `--repository` option.

**Comment by mgedmin** [comment]
> Unfortunately repozo is still using optparse so it doesn't offer clear error messages about missing arguments like that.

I wish it were using optparse!  It uses the even-older getopt :(

Anyway, I care about user experience so I'll prepare a PR to make error reporting in this case better.
