### ISSUE TITLE
Nondeterministic failure in testBogusObject (ZODB.tests.testCache.CacheErrors)?

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/ZODB#28]
I saw this error once
```
Failure in test testBogusObject (ZODB.tests.testCache.CacheErrors)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/mg/src/zopefoundation/ZODB/src/ZODB/tests/testCache.py", line 367, in testBogusObject
    self.assertEqual(sys.getrefcount(None), nones)
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 172989 != 172967
```
but was unable to reproduce it.

I was using `coverage run -m zope.testrunner --test-path=src` on Python 2.7.

**Comment by mgedmin** [comment]
Actually I can reproduce it reliably (but the actual numbers differ).

I couldn't before when I was using `nosetests --with-xcoverage`, but I can when I'm using zope.testrunner.

**Comment by mgedmin** [comment]
Ok, this is caused by the way `coverage` tracks coverage information.  Instead of using sets it uses dicts with line numbers as keys and [`None` as the value](https://github.com/nedbat/coveragepy/blob/81f5697e7cb2f5a064fd891617c0c8caf5ab21d9/coverage/tracer.c#L624).
