### ISSUE TITLE
ZODB 5.6.0 breaks as ZEO replication client against a ZODB 5.5.1 server

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/ZODB#321]
My setup has a central ZEO server running on ZODB 5.5.1 and a replicated server using `zc.zrs`. Now I updated the replication client to 5.6.0 and the first replicated transaction leads to a disconnection and the replication process breaks down:

```
2020-07-20T04:51:31 listening on /opt/buildout/var/zeoserver.soc
2020-07-20T07:40:51 IPv4Address(type='TCP', host='xxx.xxx.xxx.xxx', port=xxxx): Input data error
Traceback (most recent call last):
  File "/opt/.eggs/zc.zrs-3.1.0-py3.8.egg/zc/zrs/secondary.py", line 82, in dataReceived
    self.__stream(data)
  File "/opt/.eggs/zc.zrs-3.1.0-py3.8.egg/zc/zrs/sizedmessage.py", line 54, in __call__
    self._callback(result)
  File "/opt/.eggs/zc.zrs-3.1.0-py3.8.egg/zc/zrs/secondary.py", line 137, in messageReceived
    self.factory.storage.tpc_begin(
  File "/opt/.eggs/ZODB-5.6.0-py3.8.egg/ZODB/BaseStorage.py", line 193, in tpc_begin
    ext = transaction.extension_bytes
AttributeError: 'Transaction' object has no attribute 'extension_bytes'
```

Downgrading the replication client to ZODB 5.5.1 as workaround fixes it.

**Comment by jamadden** [comment]
This is similar to https://github.com/zopefoundation/zodbupdate/issues/35. I would say it's zc.zrs that's in the wrong here.

Storage instances in ZODB expect their `tpc_*` methods to get passed an implementation of `IStorageTransactionMetaData` (typically an instance of `ZODB.Connection.TransactionMetaData`) See [`IStorage.tpc_begin`](https://github.com/zopefoundation/ZODB/blob/22df1fd1141ab0c9db2a163799b87fe3585f15ef/src/ZODB/interfaces.py#L823-L834) for one such method.

In the past, one could get away with passing a `transaction.Transaction` object instead, because the interfaces were similar, but as-of https://github.com/zopefoundation/ZODB/pull/207, released in ZODB 5.6.0, that's no longer the case. The `messageReceived` method probably needs to change to accommodate this.
