### ISSUE TITLE
zc.zrs not working anymore

### ISSUE THREAD

**Issue by georgpfolz** [zopefoundation/ZODB#331]
## BUG/PROBLEM REPORT

ZRS stopped working with ZODB when I upgraded to Zope 5. I'm not sure if here's the right place to post this error, or if it belongs to _zc.zrs_.

Error: `AttributeError: 'Transaction' object has no attribute 'extension_bytes'` in _BaseStorage.py_, in *tcp_begin*:

```
ext = transaction.extension_bytes
```

In older versions, this line used to be:

```
ext = transaction.extension
```

### What I did:

When I start the instance on the server to which the data is replacated to, I get the following error when starting:

```
2020-10-26 22:06:16 INFO  [zc.zrs.secondary:243][MainThread] Opening /path/to/instances/myinstance/var/myinstance.fs ('my.server.ip.address', 5114)
2020-10-26 22:06:16 INFO  [zc.zrs.reactor:32][Thread-1] Starting factory <zc.zrs.secondary.SecondaryFactory object at 0x805eded30>
2020-10-26 22:06:16 INFO  [zc.zrs.secondary:70][Thread-1] IPv4Address(type='TCP', host='my.server.ip.address', port=5114): Connected
2020-10-26 22:06:16 CRITI [zc.zrs.secondary:66][Thread-1] IPv4Address(type='TCP', host='my.server.ip.address', port=5114): Input data error
Traceback (most recent call last):
  File "/usr/local/opt/Zope5/lib/python3.8/site-packages/zc/zrs/secondary.py", line 82, in dataReceived
    self.__stream(data)
  File "/usr/local/opt/Zope5/lib/python3.8/site-packages/zc/zrs/sizedmessage.py", line 54, in __call__
    self._callback(result)
  File "/usr/local/opt/Zope5/lib/python3.8/site-packages/zc/zrs/secondary.py", line 137, in messageReceived
    self.factory.storage.tpc_begin(
  File "/usr/local/opt/Zope5/lib/python3.8/site-packages/ZODB/BaseStorage.py", line 193, in tpc_begin
    ext = transaction.extension_bytes
AttributeError: 'Transaction' object has no attribute 'extension_bytes'
2020-10-26 22:06:16 INFO  [zc.zrs.secondary:70][Thread-1] IPv4Address(type='TCP', host='my.server.ip.address', port=5114): Disconnected <twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>
2020-10-26 22:06:16 INFO  [zc.zrs.reactor:32][Thread-1] Stopping factory <zc.zrs.secondary.SecondaryFactory object at 0x805eded30>
```

### What version of Python and Zope/Addons I am using:

My last version working:

- Python 3.8.6
- Zope 4.5.1
- ZODB: 5.5.1
- zc.zrs: 3.1.0

Broken in this version:

- Python 3.8.6
- Zope 5.0
- ZODB: 5.6.0
- zc.zrs: 3.1.0

**Comment by georgpfolz** [comment]
Here's probably not the right place to post this bug, it's already worked on here: https://github.com/zopefoundation/zc.zrs/issues/6
